### ISSUE TITLE
History Transaction

### ISSUE THREAD

**Issue by alifirfandi** [alifirfandi/simple-cashier-inventory#5]
This feature can be accessed either admin or super admin

- **List History Transaction**
[GET] /api/v1/history
Returns list history transaction.

- **Detail History Transaction**
[POST] /api/v1/history/{invoice}
Return history transaction data details.

- **Export History Transaction**
[PUT] /api/v1/history/pdf/{invoice}
Export one history transaction to pdf format.

**Comment by fikryfahrezy** [comment]
Can we close this @alifirfandi ? And you can delete the my [feat/product](https://github.com/alifirfandi/simple-cashier-inventory/tree/feat/product) and [feat/history](https://github.com/alifirfandi/simple-cashier-inventory/tree/feat/history) branches.
